
name: Build React App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Install Nodejs
        uses: actions/setup-node@v2.3.0
        with:
          node version: 14
          
      - name: Prepare for Yarn Installation 
        run: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      
      - name: Install Yarn
        run: sudo apt update && sudo apt install yarn
        
      - name: Build App
        run: yarn build
          
      - name: Install Surge
        run: npm install -g surge
      
      - name: Deploy to Surge
        run: surge ./build react-app-by-aqib.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
